### ISSUE TITLE
Add instructions for installing pygame.

### ISSUE THREAD

**Issue by ramaseshan** [IfetGlug/PyCam#1]
possibly
Debian : sudo apt-get install python-pygame

Fedora : sudo dnf install pygame

**Comment by iamBalaji** [comment]
issue fixed..thanks for addressing the issue..

**Comment by ramaseshan** [comment]
Can you also add instructions for fedora ?
Hope you code is not concentrated only to debian users :-)
it is 
# sudo dnf install pygame

**Comment by iamBalaji** [comment]
is it dnf or yum?

**Comment by ramaseshan** [comment]
dnf it is .
yum is deprecated.

**Comment by iamBalaji** [comment]
done..
